[package]
name = "Writer"
version = "1.0.0"
authors = []

[addresses]
deployer = "0x8480994b8cdeb0b3c6136dcc65edaafd6cd4ad18eb0d515676f3efd4dbd7d5e5"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.Oracles]
git = 'https://github.com/cnhuya/Modules.git'
rev = 'main'
subdir = 'Oracles'

[dev-dependencies]